### ISSUE TITLE
请问，这是针对Apollo哪个版本啊？

### ISSUE THREAD

**Issue by HuangCongQing** [daohu527/Dig-into-Apollo#12]

**Comment by daohu527** [comment]
Basically say, most of the tutorial is based on Apollo 3.5, I will update it to Apollo 6.0 soon.
## The plan
1. First update new functions, such as **remote control** and **v2x**.
2. Update the other modules. like perception and planning and so on.

Sorry for the plan may be a little delay. It will be very welcome if you are willing to contribute!

**Comment by daohu527** [comment]
Close the issue now, if you still have any question, you can reopen the question at any time
