### ISSUE TITLE
planning模块的readme缺图

### ISSUE THREAD

**Issue by BigBenSure** [daohu527/Dig-into-Apollo#21]
首先感谢分享这么多篇幅的apollo笔记,在阅读时我发现:

> 可以看到"OpenSpacePlanning","NaviPlanning"和"OnLanePlanning"都继承自同一个基类，并且在PlanningComponent中通过配置选择一个具体的实现进行注册。

这段话上面的图挂了.不知道是不是只有我这样.点击planning超链接,404

**Comment by BigBenSure** [comment]
#23 fixed.

**Comment by daohu527** [comment]
Thx for feedback! I will update the new version next few months.
