### ISSUE TITLE
执行过程图这里是不是反了？

### ISSUE THREAD

**Issue by Lynnonly** [daohu527/Dig-into-Apollo#26]
![image](https://user-images.githubusercontent.com/41823522/100407250-dae1d300-30a2-11eb-924e-ffbdf57e8030.png)

**Comment by Lynnonly** [comment]
https://github.com/daohu527/Dig-into-Apollo/tree/master/modules/localization

**Comment by daohu527** [comment]
Thank you for your feedback, I updated the block diagram.

`ImuCallback` and `GpsStatusCallback` are callback functions, they receive messages and run. So the direction is reversed.
