### ISSUE TITLE
高精地图

### ISSUE THREAD

**Issue by conquerw** [daohu527/dig-into-apollo#40]
1、高精度地图中使用的是WGS84坐标，为啥把坐标再转为UTM坐标系呢，还有proj4的参数为啥是这样：
        "+proj=tmerc +lat_0=37.413082 +lon_0=-122.013332 +k=0.9999999996 +ellps=WGS84 +no_defs"
        "+proj=utm +zone=50 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
     2、pj_transform转出来的坐标是三维的，为啥有些只用了二维坐标，比如（在apollo6.0中的ParsePointSet和ParseGeometry），而且向量也是二维的？在重庆感觉只使用二维好像还是找不到自己哎；
     3、使用UTM坐标系不用考虑跨区吗，疑惑中，这块怎么处理的呢？

**Comment by conquerw** [comment]
一枚小白，求各位大哥的支持

**Comment by Handy-xing** [comment]
1.proj库采用的格式就是上述格式，至于每个参数的含义可以参考proj库文档，WGS84是GPS坐标，UTM是平面坐标，利于路径规划。
2.目前没有加入三维信息坡度信息，实际上由于路的连通性，可能只是对定位的影响，对汽车的路径规划影响没那么大。
3.目前没有考虑跨区，可以优化。
(转子APollo社区)
