### ISSUE TITLE
关于"Perception/CNN/如何构建CNN"这一章节当中的一点疑问

### ISSUE THREAD

**Issue by cd4806088** [daohu527/Dig-into-Apollo#5]
你好，刚开始接触CNN的小白，对于issue标题中的那一章节中全连接层的尺寸有一些疑惑，已知卷积层2的尺寸为7 * 7，_那么池化层2中每张特征图的尺寸是不是应该是(7-2)/2+1下取整为3，即为3 * 3，而非7 * 7，所以扁平化特征图(pool2)得到的pool2_flat的尺寸就不是7 * 7 * 64，而是3 * 3 * 64了？_
今天才开始接触学习的CNN，所以也不太清楚自己的关注点正确与否， 还望指点[抱拳]

**Comment by daohu527** [comment]
因为卷积层设置的是
```
padding="same"
```
而默认步长是1，也就是说每次移动一格，如果超出则用全0补充，因此卷积层不会改变图片的大小。
28*28的图片的过程：
第一层卷积得到 32*28*28
第一层池化得到 32*14*14
第二层卷积得到 64*14*14
第一层池化得到 64*7*7

**Comment by cd4806088** [comment]
好的 我的问题是出在了第一层池化尺寸的计算上 谢谢你的悉心解答

**Comment by daohu527** [comment]
@cd4806088  欢迎分享，讨论问题 : )

**Comment by cd4806088** [comment]
一定一定 你的分享超赞[大拇指]
