### ISSUE TITLE
定位模块LidarLocator具体数据结构似未释放

### ISSUE THREAD

**Issue by TsaiHongYan** [daohu527/Dig-into-Apollo#8]
感谢您百忙之中，在知乎回答我的问题。 
在localization模块中，LidarLocator该类型好像未有具体的定义， 头文件引导“include/LidarLocator.h”但是未找到该文件。相同还有Sins类型。 其中在Localization_lidar_impl_.cc Update函数中用到LidarLocator的函数，可能用点云地图与高精度地图进行匹配（不知道我理解的对不）。

**Comment by TsaiHongYan** [comment]
我已经在阿波罗的issue看到这个问题。
if U install you apollo with docker, then this file is in your docker env. directory "/usr/local/apollo/local_integ/include/".
估计Sins类型也是同样的问题。
但是Localization里的地图还不太懂

**Comment by daohu527** [comment]
It seems that your problem has been solved 👍
